### PR TITLE
Finish adding GNOME 3.30 support

### PR DESCRIPTION
**Pull request by jtojnar**
https://github.com/medenagan/window-corner-preview/pull/7 was not enough.

### CODE REVIEW

**Comment by henryptung** [comment]
@medenagan Any issues with this? Can independently verify that the changes seem to work on my box.

Also, probable fix for #8.

**Comment by insan1k** [comment]
Confirmed that this also resolved for me running in Arch GNOME 3.30.2

**Comment by thejacer87** [comment]
works on ubuntu 18.10

thanks

**Comment by dstapp** [comment]
Also works perfectly for me on Ubuntu 18.10. Can this be merged?

**Comment by insan1k** [comment]
hey guys can someone merge this please?

**Comment by henryptung** [comment]
@medenagan Are you still maintaining this repo?

**Comment by medenagan** [comment]
Hi guys, @jtojnar commit has been merged into testing branch

**Pull request merged**
